---

- name: keys > Keys
  apt_key:
    id:             "{{ item.id }}"
    url:            "{{ item.url|default(omit) }}"
    keyserver:      "{{ item.keyserver|default(omit) }}"
    validate_certs: "{{ item.validate_certs|default(omit) }}"
    state:          "{{ item.state|default('present') }}"
  with_items: "{{ __manala_apt_keys }}"
