---

- name: keys > Keys
  apt_key:
    id:             "{{ item.id }}"
    url:            "{{ item.url|default(omit) }}"
    keyserver:      "{{ item.keyserver|default(omit) }}"
    validate_certs: "{{ item.validate_certs|default(omit) }}"
    state:          "{{ item.state|default('present') }}"
  with_manala_apt_keys:
    # Keys
    - "{{ manala_apt_keys }}"
    - "{{ manala_apt_keys_patterns }}"
    # Repositories
    - "{{ lookup(
      'manala_apt_repositories',
      manala_apt_repositories,
      manala_apt_repositories_patterns,
      manala_apt_preferences,
      wantlist=True
    ) }}"
