---

# Dependencies
- include: dependencies.yml
  tags:
    - manala_apt

# Sources list
- name: sources_list
  include: sources_list.yml
  static: false
  when: "{{
    (manala_apt_sources_list_template is not none) or (manala_apt_sources_list|length)
  }}"
  tags:
    - manala_apt

# Preferences
- name: preferences
  include: preferences.yml
  static: false
  when: "{{
    manala_apt_preferences|length
    or manala_apt_preferences_exclusive
  }}"
  tags:
    - manala_apt

# Keys
- name: keys
  include: keys.yml
  static: false
  when: "{{
    manala_apt_keys|length or manala_apt_repositories|length or manala_apt_preferences|length
  }}"
  tags:
    - manala_apt

# Repositories
- name: repositories
  include: repositories.yml
  static: false
  when: "{{
    manala_apt_repositories|length or manala_apt_preferences|length
    or manala_apt_repositories_exclusive
  }}"
  tags:
    - manala_apt

# Update
- name: update
  include: update.yml
  static: false
  when: "{{
    manala_apt['update']|default(false)
  }}"
  tags:
    - manala_apt
    - manala_apt.update
    - manala.update

# Packages
- name: packages
  include: packages.yml
  static: false
  when: "{{
    manala_apt_packages|length
  }}"
  tags:
    - manala_apt
