---

# Dependencies
- include: dependencies.yml
  tags:
    - manala_apt

# Sources list
- include: sources_list.yml
  when: (manala_apt_sources_list_template is not none) or (manala_apt_sources_list|length)
  tags:
    - manala_apt

# Vars
- include: vars.yml
  tags:
    - manala_apt

# Preferences
- include: preferences.yml
  vars:
    __manala_apt_preferences: "{{ (__manala_apt_preferences_results.results|last).ansible_facts.__item.values() if (__manala_apt_preferences_results.results|length) else [] }}"
  tags:
    - manala_apt

# Keys
- include: keys.yml
  vars:
    __manala_apt_keys: "{{ (__manala_apt_keys_results.results|last).ansible_facts.__item.values() if (__manala_apt_keys_results.results|length) else [] }}"
  tags:
    - manala_apt

# Repositories
- include: repositories.yml
  vars:
    __manala_apt_repositories: "{{ (__manala_apt_repositories_results.results|last).ansible_facts.__item.values() if (__manala_apt_repositories_results.results|length) else [] }}"
  tags:
    - manala_apt

# Upgrade
- include: upgrade.yml
  when: manala_apt_upgrade
  tags:
    - manala_apt
    - manala_apt.update
    - manala.update

# Packages
- include: packages.yml
  vars:
    __manala_apt_packages: "{{ (__manala_apt_packages_results.results|last).ansible_facts.__item.values() if (__manala_apt_packages_results.results|length) else [] }}"
  tags:
    - manala_apt
