---

# Dependencies
- import_tasks: dependencies.yml
  tags:
    - manala_apt

# Sources list
- include_tasks: sources_list.yml
  when: (manala_apt_sources_list_template is not none) or (manala_apt_sources_list|length)
  tags:
    - manala_apt

# Preferences
- import_tasks: preferences.yml
  tags:
    - manala_apt

# Keys
- import_tasks: keys.yml
  tags:
    - manala_apt

# Repositories
- import_tasks: repositories.yml
  tags:
    - manala_apt

# Update
- include_tasks: update.yml
  when: manala_apt['update']|default(false)
  tags:
    - manala_apt
    - manala_apt.update
    - manala.update

# Packages
- import_tasks: packages.yml
  tags:
    - manala_apt
