---

- name: packages > Deb present
  apt:
    deb:   "{{ item }}"
    state: present
  with_items: "{{ lookup(
      'manala_apt_packages',
      manala_apt_packages,
      wantstate='present',
      wantmap=True,
      wantdeb=True,
      wantlist=True
    )
  }}"

- name: packages > Packages present
  apt:
    package: "{{ item }}"
    state:   present
    install_recommends: false
    update_cache:       true
    cache_valid_time:   "{{ manala_apt_cache_valid_time }}"
  with_items: "{{ lookup(
      'manala_apt_packages',
      manala_apt_packages,
      wantstate='present',
      wantmap=True,
      wantdeb=False,
      wantlist=True
    )
  }}"

- name: packages > Packages absent
  apt:
    package: "{{ item }}"
    state:   absent
    purge:      true
    autoremove: true
  with_items: "{{ lookup(
      'manala_apt_packages',
      manala_apt_packages,
      wantstate='absent',
      wantmap=True,
      wantlist=True
    )
  }}"
