---

- name: sources_list > Template
  template:
    src:  "{{ manala_apt_sources_list_template|ternary(manala_apt_sources_list_template, 'sources_list/empty.j2') }}"
    dest: "{{ manala_apt_sources_list_file }}"
