---

- name: vars > Preferences
  set_fact:
    __item: "{{
      ((__manala_apt_preferences_results|default({'ansible_facts':{'__item':{}}})).ansible_facts.__item)|combine(
        (
          {
            (item.split('@')[0]).split(':')[0]: {
              'file': (item.split('@')[0]).split(':')[0],
              'package': (
                manala_apt_preferences_patterns[
                  item.split('@')[0]
                ]|default('*')
              ),
              'pin': (
                manala_apt_repositories_patterns[
                  (item.split('@')[1]|default(item)).split(':')[0]
                ].pin|default(
                  'origin ' ~ manala_apt_repositories_patterns[
                    (item.split('@')[1]|default(item)).split(':')[0]
                  ].source|regex_replace('deb https?:\\/\\/([^\\/ ]+)[\\/ ].*$', '\\1')
                )
              ),
              'priority': (item.split(':')[1]|default(900))|int
            }
          }
        ) if (item is string) else (
          {
            item.file: item
          }
        )
      )
    }}"
  with_items: "{{ manala_apt_preferences }}"
  register: __manala_apt_preferences_results

- name: vars > Preferences repositories
  set_fact:
    __item: "{{ (item.split('@')[1]|default(item)).split(':')[0] }}"
  with_items: "{{ manala_apt_preferences|select('string')|list }}"
  register: __manala_apt_preferences_repositories_results

- name: vars > Repositories
  set_fact:
    __item: "{{
      ((__manala_apt_repositories_results|default({'ansible_facts':{'__item':{}}})).ansible_facts.__item)|combine(
        (
          {
            manala_apt_repositories_patterns[item].source: manala_apt_repositories_patterns[item]
          }
        ) if (item is string) else (
          {
            item.source: item
          }
        )
      )
    }}"
  with_items: "{{ manala_apt_repositories + (__manala_apt_preferences_repositories_results.results|map(attribute='ansible_facts.__item')|list) }}"
  register: __manala_apt_repositories_results

- name: vars > Keys
  set_fact:
    __item: "{{
      ((__manala_apt_keys_results|default({'ansible_facts':{'__item':{}}})).ansible_facts.__item)|combine(
        (
          {
            manala_apt_keys_patterns[item].id: manala_apt_keys_patterns[item]
          }
        ) if (item is string) else (
          {
            item.id: item
          }
        )
      )
    }}"
  with_items: "{{
    manala_apt_keys +
    (
      (__manala_apt_repositories_results.results|last).ansible_facts.__item
        if (__manala_apt_repositories_results.results|length) else
      {}
    ).values()
      |selectattr('key', 'defined')
      |map(attribute='key')
      |list
  }}"
  register: __manala_apt_keys_results

- name: vars > Packages
  set_fact:
    __item: "{{
      ((__manala_apt_packages_results|default({'ansible_facts':{'__item':{}}})).ansible_facts.__item)|combine(
        (
          {
            item: {
              'package': item
            }
          }
        ) if (item is string) else (
          {
            item.package: item
          }
        )
      )
    }}"
  with_items: "{{ manala_apt_packages }}"
  register: __manala_apt_packages_results
